# Generated by Django 6.0.5 on 2026-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="full name"
            ),  # noqa: E501
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_lat",
            field=models.FloatField(blank=True, null=True, verbose_name="home latitude"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_lng",
            field=models.FloatField(blank=True, null=True, verbose_name="home longitude"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Providers must be verified by an admin before publishing listings. Families are verified on registration.",  # noqa: E501
                verbose_name="verified",
            ),  # noqa: E501
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="phone"
            ),  # noqa: E501
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("FAMILY", "Family"),
                    ("TUTOR", "Tutor"),
                    ("MASTERCLASS", "Masterclass"),
                    ("ADMIN", "Admin"),
                ],
                default="FAMILY",
                max_length=20,
                verbose_name="role",
            ),  # noqa: E501
        ),
    ]
