# Generated by Django 6.0.5 on 2026-06-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_populate_roles_from_legacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerDetail',
        ),
    ]
