# Generated by Django 6.0.5 on 2026-06-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="display name",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="bio"),
                ),
                (
                    "subjects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=('List of subject strings, e.g. ["Math", "Arabic"].'),
                        verbose_name="subjects",
                    ),
                ),
                (
                    "hourly_rate_qar",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="hourly rate (QAR)",
                    ),
                ),
                (
                    "availability",
                    models.TextField(blank=True, verbose_name="availability"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "provider profile",
                "verbose_name_plural": "provider profiles",
            },
        ),
    ]
