# Generated by Django 6.0.6 on 2026-06-22 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='avatar URL')),
                ('affiliation_listing_id', models.CharField(blank=True, max_length=120, verbose_name='affiliation listing ID')),
                ('subjects', models.JSONField(blank=True, default=list, verbose_name='subjects')),
                ('formats', models.JSONField(blank=True, default=list, help_text='e.g. ["ONE_ON_ONE", "SMALL_GROUP", "AT_CENTRE"]', verbose_name='formats')),
                ('age_groups', models.JSONField(blank=True, default=list, help_text='e.g. ["6-11", "12-15"]', verbose_name='age groups')),
                ('price_per_hour_qar', models.PositiveIntegerField(blank=True, null=True, verbose_name='price per hour (QAR)')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='review count')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='years of experience')),
                ('credentials', models.CharField(blank=True, max_length=300, verbose_name='credentials')),
                ('languages', models.JSONField(blank=True, default=list, help_text='e.g. ["EN", "AR"]', verbose_name='languages')),
                ('trial_available', models.BooleanField(default=False, verbose_name='trial available')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_detail', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tutor detail',
                'verbose_name_plural': 'tutor details',
            },
        ),
    ]
