# Generated by Django 6.0.6 on 2026-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_tutordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tutor subject',
                'verbose_name_plural': 'tutor subjects',
                'ordering': ['name'],
            },
        ),
    ]
