# Generated by Django 6.0.6 on 2026-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_tutorsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetail',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
