# Generated by Django 6.0.6 on 2026-06-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_providerverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderProfile',
        ),
    ]
