# Generated by Django 6.0.5 on 2026-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_delete_providerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='city'),
        ),
    ]
