# Generated by Django 6.0.5 on 2026-07-14 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_tutordetail_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetail',
            name='avatar',
        ),
        migrations.CreateModel(
            name='AvatarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='providers.tutordetail', verbose_name='tutor')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
