# Generated by Django 6.0.5 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0012_providerverification_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutordetail",
            name="subjects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Free-text subject names, e.g. ["Chemistry", "Biology"]. '
                    "Whitespace is trimmed automatically on save; matching against "
                    "the subject filter is case/whitespace-insensitive."
                ),
                verbose_name="subjects",
            ),
        ),
    ]
