# Generated by Django 6.0.5 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0012_tutordetail_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutordetail",
            name="availability",
            field=models.TextField(blank=True, verbose_name="availability"),
        ),
    ]
