# Generated by Django 6.0.5 on 2026-08-17 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0013_alter_tutordetail_subjects"),
        ("providers", "0013_providerverificationaiscreening"),
    ]

    operations = []
