# Generated by Django 6.0.5 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0013_alter_tutordetail_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutordetail",
            name="linkedin_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="LinkedIn URL"
            ),
        ),
    ]
