# Generated by Django 6.0.5 on 2026-08-19 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0014_merge_20260817_0504"),
        ("providers", "0014_tutordetail_linkedin_url"),
    ]

    operations = []
