# Generated by Django 6.0.5 on 2026-08-19 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0013_tutordetail_availability"),
        ("providers", "0015_merge_20260819_1006"),
    ]

    operations = []
