"""Tests for notifications generated by administrator-created inquiries."""

from django.contrib.auth import get_user_model
from django.test import TestCase

from apps.inquiries.models import Inquiry, InquiryStatus
from apps.notifications.models import Notification, NotificationType
from apps.notifications.tasks import notify_admin_created_inquiry
from apps.providers.models import TutorDetail
from apps.users.enums import UserRole

User = get_user_model()


class NotifyAdminCreatedInquiryTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.family = User.objects.create_user(
            email="family@test.com", password="pass1234!", role=UserRole.FAMILY
        )
        tutor_user = User.objects.create_user(
            email="tutor@test.com", password="pass1234!", role=UserRole.TUTOR
        )
        cls.tutor = TutorDetail.objects.create(user=tutor_user)

    def test_notifies_both_parties(self):
        inquiry = Inquiry.objects.create(
            family=self.family,
            tutor=self.tutor,
            message="Created by an administrator.",
            status=InquiryStatus.PENDING,
        )

        notify_admin_created_inquiry(inquiry.id)

        tutor_note = Notification.objects.get(user=self.tutor.user)
        family_note = Notification.objects.get(user=self.family)
        self.assertEqual(tutor_note.type, NotificationType.INQUIRY_REQUEST)
        self.assertEqual(family_note.type, NotificationType.INQUIRY_CREATED)
        self.assertEqual(tutor_note.data["inquiry_id"], str(inquiry.id))
        self.assertEqual(family_note.data["inquiry_id"], str(inquiry.id))

    def test_missing_inquiry_is_a_noop(self):
        notify_admin_created_inquiry("00000000-0000-0000-0000-000000000000")
        self.assertFalse(Notification.objects.exists())
