# Generated by Django 6.0.5 on 2026-06-14 09:55

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCHOOLS", "Schools"),
                            ("NURSERIES", "Nurseries"),
                            ("ACTIVITIES", "Activities"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("TUTORING", "Tutoring"),
                            ("MASTERCLASSES", "Masterclasses"),
                            ("PARTNERSHIPS", "Partnerships"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("price_from_qar", models.PositiveIntegerField(default=0)),
                ("age_groups", models.JSONField(blank=True, default=list)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("highlights", models.JSONField(blank=True, default=list)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=2,
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
