# Generated by Django 6.0.6 on 2026-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_listingclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingclient',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
