# Generated by Django 6.0.5 on 2026-06-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_listing_image_urls_listingimage'),
        ('catalog', '0004_listingclient_comment'),
    ]

    operations = [
    ]
