# Generated by Django 6.0.5 on 2026-07-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20260628_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
