# Generated by Django 6.0.5 on 2026-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_listingtag_listing_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='meeting_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
