# Generated by Django 6.0.5 on 2026-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_listingtag_order_alter_listingtag_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingtaggroup",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
    ]
