# Generated by Django 6.0.5 on 2026-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_listingtaggroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="registration_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
