# Generated by Django 6.0.5 on 2026-08-21 07:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_listing_expiry_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone"),
                            ("EMAIL", "Email"),
                            ("WEBSITE", "Website"),
                            ("WHATSAPP", "WhatsApp"),
                            ("INSTAGRAM", "Instagram"),
                            ("TELEGRAM", "Telegram"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "contact_type", "value"),
                        name="unique_contact_per_listing",
                    )
                ],
            },
        ),
    ]
