"""Canonical seed records for Qatar nurseries and kindergartens.

Each source row is preserved as a separate, self-contained dictionary. Where
an exact geocoder match or Plus Code was unavailable, coordinates use the
listed area's centre and ``exact_address`` retains the supplied address.
"""

from apps.catalog.models import ListingCategory

CATEGORY = ListingCategory.NURSERIES

NURSERIES: tuple[dict, ...] = (
    {
        "slug": "nurseries-smart-international-kindergarten",
        "title": "Smart International Kindergarten",
        "subtitle": "Kindergarten, Old Airport",
        "neighborhood": "Old Airport",
        "lat": 25.25,
        "lng": 51.56,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Old Airport. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "552 Dana St, Doha, Qatar",
        "phones": ("+974 5080 5805",),
    },
    {
        "slug": "nurseries-rising-stars-kindergarten",
        "title": "Rising Stars Kindergarten",
        "subtitle": "Kindergarten, Al Muntazah",
        "neighborhood": "Al Muntazah",
        "lat": 25.2444375,
        "lng": 51.5568125,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Al Muntazah. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "6HV4+QP6, Oqba Bin Nafie St, Doha, Qatar",
        "phones": ("+974 4467 3069",),
    },
    {
        "slug": "nurseries-kingdom-kindergarten",
        "title": "Kingdom Kindergarten",
        "subtitle": "Kindergarten, Onaiza",
        "neighborhood": "Onaiza",
        "lat": 25.3528125,
        "lng": 51.5190625,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Onaiza. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "9G39+4J3, Onaiza Street, Doha, Qatar",
        "phones": ("+974 4417 3669",),
    },
    {
        "slug": "nurseries-my-little-world-kindergarten",
        "title": "My Little World Kindergarten",
        "subtitle": "Kindergarten, Al Hilal",
        "neighborhood": "Al Hilal",
        "lat": 25.275,
        "lng": 51.55,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Al Hilal. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "Building 38, 998 Al Semaih St, Doha, Qatar",
        "phones": ("+974 4412 4382",),
    },
    {
        "slug": "nurseries-tiny-town-british-nursery",
        "title": "Tiny Town British Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 6, Street 992, Doha, Qatar",
        "phones": ("+974 6602 8092",),
    },
    {
        "slug": "nurseries-little-learners-british-nursery",
        "title": "Little Learners British Nursery",
        "subtitle": "Nursery, Al Thekhriya",
        "neighborhood": "Al Thekhriya",
        "lat": 25.2102957,
        "lng": 51.4769158,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Thekhriya. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Thekhriya Street, Doha, Qatar",
        "phones": ("+974 6604 7745",),
    },
    {
        "slug": "nurseries-little-champions-nursery",
        "title": "Little Champions Nursery",
        "subtitle": "Nursery, Abu Hamour",
        "neighborhood": "Abu Hamour",
        "lat": 25.2286,
        "lng": 51.4869,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Abu Hamour. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "90 Heenat Al Meashab St, Abu Hamour, Doha, Qatar",
        "phones": ("+974 4416 1497",),
    },
    {
        "slug": "nurseries-apple-tree-nursery",
        "title": "Apple Tree Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Tuwaim Street, Doha, Qatar",
        "phones": ("+974 5015 2325",),
    },
    {
        "slug": "nurseries-fairy-tales-nursery-ain-khaled",
        "title": "Fairy Tales Nursery – Ain Khaled",
        "subtitle": "Nursery, Ain Khaled",
        "neighborhood": "Ain Khaled",
        "lat": 25.22,
        "lng": 51.43,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Ain Khaled. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 87, 670 Wadi Al Utiiriya St, Doha, Qatar",
        "phones": ("+974 4498 9478",),
    },
    {
        "slug": "nurseries-erin-mills-nursery",
        "title": "Erin Mills Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 9, Al Furousiya St, in front of Doha Zoo, Al Waab, Doha",
        "phones": ("+974 4017 4984", "+974 6609 1400"),
    },
    {
        "slug": "nurseries-future-kids-nursery",
        "title": "Future Kids Nursery",
        "subtitle": "Nursery, Al Khuraitiyat",
        "neighborhood": "Al Khuraitiyat",
        "lat": 25.39,
        "lng": 51.42,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Khuraitiyat. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 26, Street 77, Al Khuraitiyat, Doha",
        "phones": ("+974 4483 7162", "+974 6662 2408", "+974 7022 2408"),
    },
    {
        "slug": "nurseries-blossom-nursery",
        "title": "Blossom Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 25, Street 2, Al Waab, Doha",
        "phones": ("+974 4447 2266", "+974 4447 2288", "+974 6660 3642"),
    },
    {
        "slug": "nurseries-homey-nursery",
        "title": "Homey Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 12, Street 226, Zone 55, Al Waab, Doha",
        "phones": ("+974 4469 1918", "+974 6609 2211"),
    },
    {
        "slug": "nurseries-al-numan-nursery",
        "title": "Al Numan Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4487 8575",),
    },
    {
        "slug": "nurseries-we-care-nursery",
        "title": "We Care Nursery",
        "subtitle": "Nursery, Al Thumama",
        "neighborhood": "Al Thumama",
        "lat": 25.22,
        "lng": 51.56,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Thumama. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "East Ring Road, Al Thumama, Doha",
        "phones": ("+974 4411 3839", "+974 3321 7621", "+974 7099 4665"),
    },
    {
        "slug": "nurseries-al-shomooa-nursery",
        "title": "Al Shomooa Nursery",
        "subtitle": "Nursery, Old Airport",
        "neighborhood": "Old Airport",
        "lat": 25.25,
        "lng": 51.56,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Old Airport. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "D Ring Road, near Lulu Market, Old Airport, Doha",
        "phones": ("+974 4467 5575", "+974 4467 6760"),
    },
    {
        "slug": "nurseries-sunrise-nursery",
        "title": "Sunrise Nursery",
        "subtitle": "Nursery, Madinat Khalifa North",
        "neighborhood": "Madinat Khalifa North",
        "lat": 25.33,
        "lng": 51.48,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Madinat Khalifa North. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Arab League St, near Dahl Al Hamam Park, Doha",
        "phones": ("+974 4488 4474", "+974 3341 1367"),
    },
    {
        "slug": "nurseries-sara-nursery",
        "title": "Sara Nursery",
        "subtitle": "Nursery, Al Maamoura",
        "neighborhood": "Al Maamoura",
        "lat": 25.25,
        "lng": 51.51,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Maamoura. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 1, Bin Al Qantari St, Al Maamoura, Doha",
        "phones": ("+974 4481 7738", "+974 6666 3451"),
    },
    {
        "slug": "nurseries-fun-first-nursery",
        "title": "Fun First Nursery",
        "subtitle": "Nursery, West Bay Lagoon",
        "neighborhood": "West Bay Lagoon",
        "lat": 25.36,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay Lagoon. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Saha 47, Doha, Qatar",
        "phones": ("+974 4411 0953",),
    },
    {
        "slug": "nurseries-grandma-nursery-3",
        "title": "Grandma Nursery 3",
        "subtitle": "Nursery, Al Maamoura",
        "neighborhood": "Al Maamoura",
        "lat": 25.25,
        "lng": 51.51,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Maamoura. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa No., Area 56, Street 706, Al Maamoura, Doha",
        "phones": ("+974 4414 4008",),
    },
    {
        "slug": "nurseries-royal-kids-nursery",
        "title": "Royal Kids Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.3128125,
        "lng": 51.4645625,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "8F77+4RH, Makkah Street, Doha",
        "phones": ("+974 3106 9692",),
    },
    {
        "slug": "nurseries-starfish-lane-kids-4",
        "title": "Starfish Lane Kids 4",
        "subtitle": "Nursery, Zone 56",
        "neighborhood": "Zone 56",
        "lat": 25.23,
        "lng": 51.49,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Zone 56. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Wadi Al Shaheeniya St, Villa 40, Ras Al Mearad St, Zone 56, Doha",
        "phones": ("+974 4436 3592",),
    },
    {
        "slug": "nurseries-bambinos-day-care-2",
        "title": "Bambinos Day Care 2",
        "subtitle": "Day Care / Nursery, Al Markhiya",
        "neighborhood": "Al Markhiya",
        "lat": 25.3282,
        "lng": 51.4936,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Day Care / Nursery located in Al Markhiya. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Day Care / Nursery"],
        "tags": [],
        "exact_address": "Al Markhiya St, Doha",
        "phones": ("+974 3000 1884",),
    },
    {
        "slug": "nurseries-little-steamers-nursery",
        "title": "Little Steamers Nursery",
        "subtitle": "Nursery, Al Markhiya",
        "neighborhood": "Al Markhiya",
        "lat": 25.3282,
        "lng": 51.4936,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Markhiya. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 6, Street 998, Arab League St, Zone 67, Doha",
        "phones": ("+974 4411 0027", "+974 5043 6846"),
    },
    {
        "slug": "nurseries-creative-child-nursery",
        "title": "Creative Child Nursery",
        "subtitle": "Nursery, Al Duhail",
        "neighborhood": "Al Duhail",
        "lat": 25.35,
        "lng": 51.48,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Duhail. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Duhail, Doha",
        "phones": ("+974 4479 5916",),
    },
    {
        "slug": "nurseries-cocorico-nursery",
        "title": "Cocorico Nursery",
        "subtitle": "Nursery, Al Markhiya",
        "neighborhood": "Al Markhiya",
        "lat": 25.3282,
        "lng": 51.4936,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Markhiya. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Near Al Ahli Hospital, Al Markhiya, Doha",
        "phones": ("+974 4488 1583", "+974 5515 1708"),
    },
    {
        "slug": "nurseries-daffodils-nursery",
        "title": "Daffodils Nursery",
        "subtitle": "Nursery, Old Airport",
        "neighborhood": "Old Airport",
        "lat": 25.25,
        "lng": 51.56,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Old Airport. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Ahmed Bin Hanbal St, Doha",
        "phones": ("+974 4466 4573",),
    },
    {
        "slug": "nurseries-kinder-academy-nursery",
        "title": "Kinder Academy Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4411 9444",),
    },
    {
        "slug": "nurseries-koala-nursery",
        "title": "Koala Nursery",
        "subtitle": "Nursery, West Bay / Al Dafna",
        "neighborhood": "West Bay / Al Dafna",
        "lat": 25.33,
        "lng": 51.53,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay / Al Dafna. Contact and location details "
        "are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "United Nations St, opposite Lebanese School, Doha",
        "phones": ("+974 4491 8811",),
    },
    {
        "slug": "nurseries-life-time-nursery",
        "title": "Life Time Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4455 1010",),
    },
    {
        "slug": "nurseries-little-butterflies-nursery",
        "title": "Little Butterflies Nursery",
        "subtitle": "Nursery, Al Duhail",
        "neighborhood": "Al Duhail",
        "lat": 25.35,
        "lng": 51.48,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Duhail. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Khafji St, opposite Riviera Gardens, Doha",
        "phones": ("+974 4412 5187",),
    },
    {
        "slug": "nurseries-little-genius-nursery",
        "title": "Little Genius Nursery",
        "subtitle": "Nursery, West Bay",
        "neighborhood": "West Bay",
        "lat": 25.33,
        "lng": 51.53,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Jelailah, West Bay, Doha",
        "phones": ("+974 4483 3591",),
    },
    {
        "slug": "nurseries-little-lions-english-nursery",
        "title": "Little Lions English Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4441 3094",),
    },
    {
        "slug": "nurseries-giggles-day-care",
        "title": "Giggles Day Care",
        "subtitle": "Nursery / Day Care, Al Gharrafa",
        "neighborhood": "Al Gharrafa",
        "lat": 25.33,
        "lng": 51.44,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery / Day Care located in Al Gharrafa. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery / Day Care"],
        "tags": [],
        "exact_address": "Al Gharrafa, Al Rayyan, Qatar",
        "phones": ("+974 4434 2371",),
    },
    {
        "slug": "nurseries-green-apple-nursery",
        "title": "Green Apple Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4411 1431",),
    },
    {
        "slug": "nurseries-happy-faces-nursery",
        "title": "Happy Faces Nursery",
        "subtitle": "Nursery, Al Hilal",
        "neighborhood": "Al Hilal",
        "lat": 25.275,
        "lng": 51.55,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Hilal. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Zone 41, Building 14, Street 859, Doha",
        "phones": ("+974 4466 6178", "+974 3029 6969"),
    },
    {
        "slug": "nurseries-honeypot-nursery",
        "title": "Honeypot Nursery",
        "subtitle": "Nursery, Al Aziziyah",
        "neighborhood": "Al Aziziyah",
        "lat": 25.25,
        "lng": 51.44,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Aziziyah. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Nahawand St, Al Aziziyah, Doha",
        "phones": ("+974 4467 7409",),
    },
    {
        "slug": "nurseries-jasmine-private-kindergarten",
        "title": "Jasmine Private Kindergarten",
        "subtitle": "Kindergarten, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Doha. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4487 4539",),
    },
    {
        "slug": "nurseries-juniors-nursery",
        "title": "Juniors Nursery",
        "subtitle": "Nursery, Al Shuwala",
        "neighborhood": "Al Shuwala",
        "lat": 25.3,
        "lng": 51.47,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Shuwala. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 50, Al Shuwala St 134, Doha",
        "phones": ("+974 4413 4242",),
    },
    {
        "slug": "nurseries-kids-r-us",
        "title": "Kids R Us",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4411 3483",),
    },
    {
        "slug": "nurseries-al-bateel-international-kindergarten",
        "title": "Al Bateel International Kindergarten",
        "subtitle": "International Kindergarten, Al Mamoura",
        "neighborhood": "Al Mamoura",
        "lat": 25.25,
        "lng": 51.51,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "International Kindergarten located in Al Mamoura. Contact and "
        "location details are maintained as editorial catalog data.",
        "highlights": ["International Kindergarten"],
        "tags": [],
        "exact_address": "Near Dhreima, Al Mamoura, Doha, Qatar",
        "phones": ("+974 6606 2304",),
    },
    {
        "slug": "nurseries-apple-tree-nursery-2",
        "title": "Apple Tree Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Waab, Doha, Qatar",
        "phones": ("+974 4481 7010", "+974 5015 2325"),
    },
    {
        "slug": "nurseries-baby-planet-nursery",
        "title": "Baby Planet Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4412 9684",),
    },
    {
        "slug": "nurseries-bambinos-nursery",
        "title": "Bambinos Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4444 1020",),
    },
    {
        "slug": "nurseries-blue-bells-nursery",
        "title": "Blue Bells Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4488 3072",),
    },
    {
        "slug": "nurseries-bright-beginnings-nursery",
        "title": "Bright Beginnings Nursery",
        "subtitle": "Nursery, Muaither",
        "neighborhood": "Muaither",
        "lat": 25.29,
        "lng": 51.4,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Muaither. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Muaither Sports Club area, Al Rayyan, Qatar",
        "phones": ("+974 4463 4630",),
    },
    {
        "slug": "nurseries-bunny-english-nursery",
        "title": "Bunny English Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Emir Street / Al Waab area, Doha, Qatar",
        "phones": ("+974 4450 7012",),
    },
    {
        "slug": "nurseries-busy-bees-nursery",
        "title": "Busy Bees Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Emir Street, Al Waab, Doha, Qatar",
        "phones": ("+974 4447 2319",),
    },
    {
        "slug": "nurseries-busy-hands-nursery",
        "title": "Busy Hands Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4487 3214",),
    },
    {
        "slug": "nurseries-junior-nursery",
        "title": "Junior Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4413 4242",),
    },
    {
        "slug": "nurseries-kangaroo-kids",
        "title": "Kangaroo Kids",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4444 2545",),
    },
    {
        "slug": "nurseries-kids-for-care",
        "title": "Kids for Care",
        "subtitle": "Nursery / Day Care, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery / Day Care located in Doha. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery / Day Care"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4466 7702",),
    },
    {
        "slug": "nurseries-kingsway-nursery",
        "title": "Kingsway Nursery",
        "subtitle": "Nursery, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Doha. Contact and location details are maintained "
        "as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4472 9731",),
    },
    {
        "slug": "nurseries-little-angels-academy",
        "title": "Little Angels Academy",
        "subtitle": "Nursery / Early Years, Al Maamoura",
        "neighborhood": "Al Maamoura",
        "lat": 25.25,
        "lng": 51.51,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery / Early Years located in Al Maamoura. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery / Early Years"],
        "tags": [],
        "exact_address": "Al Maamoura, Doha, Qatar",
        "phones": ("+974 4460 2713",),
    },
    {
        "slug": "nurseries-the-little-hands-nursery",
        "title": "The Little Hands Nursery",
        "subtitle": "Nursery, New Salatah",
        "neighborhood": "New Salatah",
        "lat": 25.26,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in New Salatah. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "850 Al Mishaal Street, New Salatah, Doha, Qatar",
        "phones": ("+974 5515 1113",),
    },
    {
        "slug": "nurseries-acorn-nursery-ain-khalid",
        "title": "Acorn Nursery – Ain Khalid",
        "subtitle": "Nursery, Ain Khalid",
        "neighborhood": "Ain Khalid",
        "lat": 25.22,
        "lng": 51.43,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Ain Khalid. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "24 Rawdat Umm Al Lekhsaf St, Doha, Qatar",
        "phones": ("+974 4038 7684",),
    },
    {
        "slug": "nurseries-cuddle-castle-nursery",
        "title": "Cuddle Castle Nursery",
        "subtitle": "Nursery, North Duhail",
        "neighborhood": "North Duhail",
        "lat": 25.37,
        "lng": 51.48,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in North Duhail. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "North Duhail, Doha, Qatar",
        "phones": ("+974 7059 0999",),
    },
    {
        "slug": "nurseries-juniors-nursery-baby-care",
        "title": "Juniors Nursery & Baby Care",
        "subtitle": "Nursery, Al Aziziyah",
        "neighborhood": "Al Aziziyah",
        "lat": 25.25,
        "lng": 51.44,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Aziziyah. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Aziziyah, Doha, Qatar",
        "phones": ("+974 4451 4382",),
    },
    {
        "slug": "nurseries-acorn-nursery-al-khor",
        "title": "Acorn Nursery – Al Khor",
        "subtitle": "Nursery, Al Khor",
        "neighborhood": "Al Khor",
        "lat": 25.7099222,
        "lng": 51.5254982,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Khor. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Khor, Qatar",
        "phones": ("+974 4471 3597", "+974 5066 2510"),
    },
    {
        "slug": "nurseries-al-maha-kindergarten",
        "title": "Al Maha Kindergarten",
        "subtitle": "Kindergarten, Doha",
        "neighborhood": "Doha",
        "lat": 25.2856,
        "lng": 51.5264,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Doha. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "Doha, Qatar",
        "phones": ("+974 4469 9294",),
    },
    {
        "slug": "nurseries-qatar-international-nursery",
        "title": "Qatar International Nursery",
        "subtitle": "Nursery, Al Rehab",
        "neighborhood": "Al Rehab",
        "lat": 25.26,
        "lng": 51.49,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Rehab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Rehab Street, near Omani Market, Doha, Qatar",
        "phones": ("+974 4421 2630",),
    },
    {
        "slug": "nurseries-footsteps-nursery",
        "title": "Footsteps Nursery",
        "subtitle": "Nursery, Al Ghanim",
        "neighborhood": "Al Ghanim",
        "lat": 25.29,
        "lng": 51.54,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Ghanim. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 265, 420 Ammar Bin Yasser Street, Zone 55, Al Ghanim, "
        "Qatar",
        "phones": ("+974 5045 1840",),
    },
    {
        "slug": "nurseries-bright-horizon-international-kindergarten",
        "title": "Bright Horizon International Kindergarten",
        "subtitle": "International Kindergarten, Al Taif",
        "neighborhood": "Al Taif",
        "lat": 25.34,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "International Kindergarten located in Al Taif. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["International Kindergarten"],
        "tags": [],
        "exact_address": "Al Taif St, Doha, Qatar",
        "phones": (),
    },
    {
        "slug": "nurseries-french-nursery",
        "title": "French Nursery",
        "subtitle": "Nursery, Madinat Khalifa South",
        "neighborhood": "Madinat Khalifa South",
        "lat": 25.32,
        "lng": 51.49,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Madinat Khalifa South. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Ibn Arabi St, Madinat Khalifa South, Doha, Qatar",
        "phones": (),
    },
    {
        "slug": "nurseries-edison-nursery",
        "title": "Edison Nursery",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Waab St, near Khalifa Stadium, Doha, Qatar",
        "phones": (),
    },
    {
        "slug": "nurseries-little-village-nursery",
        "title": "Little Village Nursery",
        "subtitle": "Nursery, Madinat Khalifa South",
        "neighborhood": "Madinat Khalifa South",
        "lat": 25.32,
        "lng": 51.49,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Madinat Khalifa South. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 136, Al Jazeera Al Arabia St, Madinat Khalifa South, Doha, "
        "Qatar",
        "phones": ("+974 4421 7775",),
    },
    {
        "slug": "nurseries-nannys-home-nursery",
        "title": "Nanny's Home Nursery",
        "subtitle": "Nursery, Al Thumama",
        "neighborhood": "Al Thumama",
        "lat": 25.22,
        "lng": 51.56,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Thumama. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Thumama, Doha, Qatar",
        "phones": ("+974 4443 5356", "+974 3335 3536"),
    },
    {
        "slug": "nurseries-al-sama-nursery",
        "title": "Al Sama Nursery",
        "subtitle": "Nursery, Izghawa",
        "neighborhood": "Izghawa",
        "lat": 25.38,
        "lng": 51.42,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Izghawa. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Doha Expressway, behind Taibah Petrol Station, Izghawa, Al Rayyan, "
        "Qatar",
        "phones": ("+974 4479 2576", "+974 6634 4633"),
    },
    {
        "slug": "nurseries-future-nursery",
        "title": "Future Nursery",
        "subtitle": "Nursery, Abu Hamour",
        "neighborhood": "Abu Hamour",
        "lat": 25.2286,
        "lng": 51.4869,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Abu Hamour. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Behind Ooredoo Tower, Abu Hamour, Doha, Qatar",
        "phones": ("+974 4450 1264", "+974 6666 0320"),
    },
    {
        "slug": "nurseries-hello-baby-nursery",
        "title": "Hello Baby Nursery",
        "subtitle": "Nursery, Abu Hamour",
        "neighborhood": "Abu Hamour",
        "lat": 25.2286,
        "lng": 51.4869,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Abu Hamour. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 20, in front of Al Fardan Gardens 3, Abu Hamour, Doha, Qatar",
        "phones": ("+974 4416 1497", "+974 7775 9789"),
    },
    {
        "slug": "nurseries-the-english-kindergarten",
        "title": "The English Kindergarten",
        "subtitle": "Kindergarten, Al Maamoura",
        "neighborhood": "Al Maamoura",
        "lat": 25.25,
        "lng": 51.51,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Kindergarten located in Al Maamoura. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Kindergarten"],
        "tags": [],
        "exact_address": "Villa 13, Mansour Bin Talha St No. 652, Al Maamoura, Doha, Qatar",
        "phones": (),
    },
    {
        "slug": "nurseries-caia-nursery",
        "title": "Caia Nursery",
        "subtitle": "Nursery, Hazm el Markhiya",
        "neighborhood": "Hazm el Markhiya",
        "lat": 25.35,
        "lng": 51.47,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Hazm el Markhiya. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Street 903, Villa 3, Zone 67, Hazm el Markhiya, Doha, Qatar",
        "phones": ("+974 5991 1434",),
    },
    {
        "slug": "nurseries-the-nest-nursery",
        "title": "The Nest Nursery",
        "subtitle": "Nursery, Legtaifiya",
        "neighborhood": "Legtaifiya",
        "lat": 25.37,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Legtaifiya. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 123, Street 742, Zone 66, Legtaifiya, Doha, Qatar",
        "phones": ("+974 5534 8947",),
    },
    {
        "slug": "nurseries-tlc-nursery-west-bay",
        "title": "TLC Nursery West Bay",
        "subtitle": "Nursery, West Bay Lagoon",
        "neighborhood": "West Bay Lagoon",
        "lat": 25.36,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay Lagoon. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "64 Al Jamiaa St, West Bay Lagoon, Doha, Qatar",
        "phones": ("+974 7069 8508",),
    },
    {
        "slug": "nurseries-tlc-nursery-mamoura",
        "title": "TLC Nursery Mamoura",
        "subtitle": "Nursery, Al Maamoura",
        "neighborhood": "Al Maamoura",
        "lat": 25.25,
        "lng": 51.51,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Maamoura. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Maadeed St, Al Maamoura, Doha, Qatar",
        "phones": ("+974 7780 0852",),
    },
    {
        "slug": "nurseries-tlc-nursery-msheireb",
        "title": "TLC Nursery Msheireb",
        "subtitle": "Nursery, Msheireb Downtown",
        "neighborhood": "Msheireb Downtown",
        "lat": 25.286,
        "lng": 51.527,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Msheireb Downtown. Contact and location details "
        "are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 49, Street 980, Zone 3, Al Kahraba St, Msheireb Downtown, "
        "Doha, Qatar",
        "phones": ("+974 7737 7852",),
    },
    {
        "slug": "nurseries-primrose-nursery-al-waab",
        "title": "Primrose Nursery – Al Waab",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Waab Street, Doha, Qatar",
        "phones": ("+974 4417 6744", "+974 3355 4004"),
    },
    {
        "slug": "nurseries-primrose-nursery-west-bay",
        "title": "Primrose Nursery – West Bay",
        "subtitle": "Nursery, West Bay",
        "neighborhood": "West Bay",
        "lat": 25.33,
        "lng": 51.53,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "West Bay, Doha, Qatar",
        "phones": ("+974 4488 5941", "+974 6699 3373"),
    },
    {
        "slug": "nurseries-grandma-nursery-1",
        "title": "Grandma Nursery 1",
        "subtitle": "Nursery, West Bay / Onaizah 63",
        "neighborhood": "West Bay / Onaizah 63",
        "lat": 25.35,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay / Onaizah 63. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 52, El Eithar Street No. 941, Onaizah 63, West Bay, Doha, "
        "Qatar",
        "phones": ("+974 4488 4008", "+974 3344 4008"),
    },
    {
        "slug": "nurseries-grandma-nursery-2",
        "title": "Grandma Nursery 2",
        "subtitle": "Nursery, West Bay / Onaizah 65",
        "neighborhood": "West Bay / Onaizah 65",
        "lat": 25.36,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay / Onaizah 65. Contact and location "
        "details are maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 4, Al Huda Street No. 810, Onaizah 65, West Bay, Doha, Qatar",
        "phones": ("+974 4488 4003", "+974 6644 4003"),
    },
    {
        "slug": "nurseries-grandma-nursery-4",
        "title": "Grandma Nursery 4",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2606,
        "lng": 51.4494,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 108, Main Street Al Waab No. 364, Area 54, Al Waab, Doha, "
        "Qatar",
        "phones": ("+974 4441 3008", "+974 5028 0011"),
    },
    {
        "slug": "nurseries-redwood-montessori-nursery-al-dafna",
        "title": "Redwood Montessori Nursery – Al Dafna",
        "subtitle": "Nursery, Al Dafna",
        "neighborhood": "Al Dafna",
        "lat": 25.33,
        "lng": 51.53,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Dafna. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 182, Zone 66, Street 801, Doha, Qatar",
        "phones": ("+974 7093 9837",),
    },
    {
        "slug": "nurseries-redwood-montessori-nursery-al-waab",
        "title": "Redwood Montessori Nursery – Al Waab",
        "subtitle": "Nursery, Al Waab",
        "neighborhood": "Al Waab",
        "lat": 25.2694375,
        "lng": 51.4658125,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Waab. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "7F98+Q88, Al Waab, Doha, Qatar",
        "phones": ("+974 3100 7117",),
    },
    {
        "slug": "nurseries-starfish-lane-kids-1",
        "title": "Starfish Lane Kids 1",
        "subtitle": "Nursery, Al Markhiya",
        "neighborhood": "Al Markhiya",
        "lat": 25.3282,
        "lng": 51.4936,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Markhiya. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 30, Street 803, Zone 33, Al Markhiya, Doha, Qatar",
        "phones": ("+974 4487 5939",),
    },
    {
        "slug": "nurseries-starfish-lane-kids-2",
        "title": "Starfish Lane Kids 2",
        "subtitle": "Nursery, Al Jelaiah",
        "neighborhood": "Al Jelaiah",
        "lat": 25.35,
        "lng": 51.5,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Jelaiah. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Zone 68, Street 951, off Jelaiah Street, Doha, Qatar",
        "phones": ("+974 4411 0355",),
    },
    {
        "slug": "nurseries-juniors-nursery-al-aziziyah",
        "title": "Juniors Nursery – Al Aziziyah",
        "subtitle": "Nursery, Al Aziziyah",
        "neighborhood": "Al Aziziyah",
        "lat": 25.25,
        "lng": 51.44,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Al Aziziyah. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 6, Zone 55, Area 53, Doha, Qatar",
        "phones": ("+974 4451 4382", "+974 6662 2870"),
    },
    {
        "slug": "nurseries-juniors-nursery-ras-bu-fantas",
        "title": "Juniors Nursery – Ras Bu Fantas",
        "subtitle": "Nursery, Ras Bu Fantas",
        "neighborhood": "Ras Bu Fantas",
        "lat": 25.2,
        "lng": 51.6,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Ras Bu Fantas. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 12, Zone 55, Street 226, Ras Bu Fantas, Doha, Qatar",
        "phones": ("+974 4469 1918", "+974 6609 2211"),
    },
    {
        "slug": "nurseries-fairy-tales-nursery-west-bay",
        "title": "Fairy Tales Nursery – West Bay",
        "subtitle": "Nursery, West Bay",
        "neighborhood": "West Bay",
        "lat": 25.33,
        "lng": 51.53,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in West Bay. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Al Istiqlal Street, West Bay, Doha, Qatar",
        "phones": ("+974 4417 8880", "+974 3366 9620"),
    },
    {
        "slug": "nurseries-lifetime-nursery-onaiza",
        "title": "Lifetime Nursery – Onaiza",
        "subtitle": "Nursery, Onaiza",
        "neighborhood": "Onaiza",
        "lat": 25.34,
        "lng": 51.52,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Onaiza. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Building 23, Zone 65, Al Baghla Street, Onaiza, Doha, Qatar",
        "phones": ("+974 5114 0114",),
    },
    {
        "slug": "nurseries-honeypot-nursery-nuaija",
        "title": "Honeypot Nursery – Nuaija",
        "subtitle": "Nursery, Nuaija",
        "neighborhood": "Nuaija",
        "lat": 25.25,
        "lng": 51.53,
        "price_from_qar": 0,
        "age_groups": ["0-3", "3-5"],
        "description": "Nursery located in Nuaija. Contact and location details are "
        "maintained as editorial catalog data.",
        "highlights": ["Nursery"],
        "tags": [],
        "exact_address": "Villa 36, Area 43, Street 987, Al Mashaill Street, Nuaija, Doha, "
        "Qatar",
        "phones": ("+974 7066 0039",),
    },
)

assert len(NURSERIES) == 90, f"Expected 90 nurseries, got {len(NURSERIES)}"
assert len({item["slug"] for item in NURSERIES}) == len(NURSERIES)
