# Generated by Django 6.0.6 on 2026-06-30 06:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_delete_providerprofile'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_reviews_written', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_reviews', to='providers.tutordetail')),
            ],
            options={
                'verbose_name': 'tutor review',
                'verbose_name_plural': 'tutor reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tutor', 'author'), name='unique_review_per_tutor_author')],
            },
        ),
    ]
