# Generated by Django 6.0.5 on 2026-07-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROVIDER_APPROVED', 'Provider application approved'), ('PROVIDER_REJECTED', 'Provider application rejected'), ('LISTING_APPROVED', 'Listing applicatoin approved'), ('LISTING_REJECTED', 'Listing application rejected'), ('INQUIRY_RESPONSE', 'Inquiry responded'), ('INQUIRY_REQUEST', 'Inquiry requested')], max_length=40, verbose_name='type'),
        ),
    ]
