# Generated by Django 6.0.5 on 2026-08-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROVIDER_APPROVED', 'Provider application approved'), ('PROVIDER_REJECTED', 'Provider application rejected'), ('LISTING_APPROVED', 'Listing applicatoin approved'), ('LISTING_REJECTED', 'Listing application rejected'), ('INQUIRY_RESPONSE', 'Inquiry responded'), ('INQUIRY_REQUEST', 'Inquiry requested'), ('INQUIRY_CREATED', 'Inquiry created by administrator'), ('INQUIRY_CANCEL', 'Inquiry cancelled')], max_length=40, verbose_name='type'),
        ),
    ]
